#!/bin/bash
# This is a simple build script, place your post-deploy but pre-start commands
# in this script.  This script gets executed directly, so it could be python,
# php, ruby, etc.

set -x
cd $OPENSHIFT_REPO_DIR/src/main/resources/META-INF
sed -ig 's/OPENSHIFT_APP_NAME/'$OPENSHIFT_APP_NAME'/g' persistence.xml
sed -ig 's/OPENSHIFT_NOSQL_DB_HOST/'$OPENSHIFT_NOSQL_DB_HOST'/g' persistence.xml
sed -ig 's/OPENSHIFT_NOSQL_DB_PORT/'$OPENSHIFT_NOSQL_DB_PORT'/g' persistence.xml
sed -ig 's/OPENSHIFT_NOSQL_DB_USERNAME/'$OPENSHIFT_NOSQL_DB_USERNAME'/g' persistence.xml
sed -ig 's/OPENSHIFT_NOSQL_DB_PASSWORD/'$OPENSHIFT_NOSQL_DB_PASSWORD'/g' persistence.xml
