#!/bin/bash
set -x
cd $OPENSHIFT_REPO_DIR/src/main/resources/META-INF
sed -ig 's/OPENSHIFT_APP_NAME/'$OPENSHIFT_APP_NAME'/g' persistence.xml
sed -ig 's/OPENSHIFT_MONGODB_DB_HOST/'$OPENSHIFT_MONGODB_DB_HOST'/g' persistence.xml
sed -ig 's/OPENSHIFT_MONGODB_DB_PORT/'$OPENSHIFT_MONGODB_DB_PORT'/g' persistence.xml
sed -ig 's/OPENSHIFT_MONGODB_DB_USERNAME/'$OPENSHIFT_MONGODB_DB_USERNAME'/g' persistence.xml
sed -ig 's/OPENSHIFT_MONGODB_DB_PASSWORD/'$OPENSHIFT_MONGODB_DB_PASSWORD'/g' persistence.xml
